services:
  - type: web
    name: railway-reservation-api
    runtime: docker
    dockerfilePath: Backend/railway-reservation/railway-reservation/Dockerfile
    dockerContext: Backend/railway-reservation/railway-reservation
    envVars:
      - key: JAVA_VERSION
        value: "25"
      - key: MYSQLHOST
        value: railway-reservation-db-urvashisingh468-381b.d.aivencloud.com
      - key: MYSQLPORT
        value: "24679"
      - key: MYSQLDATABASE
        value: defaultdb
      - key: MYSQLUSER
        value: avnadmin
      - key: MYSQLSSLMODE
        value: REQUIRED
      - key: MYSQLPASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
