services:
  - type: web
    name: railway-reservation-api
    runtime: docker
    dockerfilePath: Backend/railway-reservation/railway-reservation/Dockerfile
    dockerContext: Backend/railway-reservation/railway-reservation
    envVars:
      - key: JAVA_VERSION
        value: "25"
      - key: MYSQLHOST
        sync: false
      - key: MYSQLPORT
        sync: false
      - key: MYSQLDATABASE
        sync: false
      - key: MYSQLUSER
        sync: false
      - key: MYSQLPASSWORD
        sync: false
